.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "TOXDUMP" "1" "February 2015" "" ""
.
.SH "NAME"
\fBtoxdump\fR \- dump tox files to other formats
.
.SH "SYNOPSIS"
\fBtoxdump\fR [\fIoptions\fR\.\.\.] \fIfile\fR
.
.SH "DESCRIPTION"
\fBtoxdump\fR is a utility for dumping tox files to other formats\.
.
.SH "OPTIONS"
.
.TP
\fB\-j\fR, \fB\-\-json\fR
Use JSON as the format to dump to\.
.
.TP
\fB\-n\fR, \fB\-\-no\-newline\fR
Don\'t print a newline after dumping toxfile data\.
.
.TP
\fB\-p\fR, \fB\-\-profile\fR=\fIprofile\fR
Specify the profile name to use when looking for a tox file\. This will look for ~/\.config/tox/\fIprofile\fR\.tox and use it as the tox file if found\.
.
.TP
\fB\-v\fR, \fB\-\-version\fR
Print toxdump\'s version and exit\.
.
.TP
\fB\-x\fR, \fB\-\-include\-private\-key\fR
Include the private key in the output\.
.
.TP
\fB\-X\fR, \fB\-\-hex\-uppercase\fR
Dump hex strings as uppercase\. This affects the address, public key and private key\.
.
.SH "GITHUB"
https://github\.com/saneki/toxfile
